version: '3.8'
services:
  expense-tracker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: guptaritik2712/expense-tracker-app
    ports:
      - "3000:80"
    restart: unless-stopped